### ISSUE TITLE
Adaptive roadmap

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#766]
* [ ] - Is outcome/objective/competency based (not chapter based),
* [ ] - Presents adaptive content & assessments based on analytics (student model/ domain model)
* [ ] - Personalized path: prerequisite, (accelerate or remediate) (system meets student’s needs) adapt to students’ knowledge; Provides real-time analytics (student model/ domain model), and recommends personalized interventions (feedback)
* [ ] - Presents alternative adaptive contents presentation (video, text, etc.) based on learning styles/ learner preferences and learning characteristics; what’s optimal for each student, deliver learning path and resources accordingly (machine learning)
* [ ] - Procedurally generates questions and contents using variable, conditions

**Comment by zachberry** [comment]
Closing as this issue is too general. For our current roadmap on this see https://github.com/ucfopen/Obojobo/wiki/Project-Roadmap .
